version: '3.8'

volumes:
  pg_data:
  static:
  media:
  letsencrypt_etc:      # ← новый том для сертификатов
  letsencrypt_var:      # ← опционально, но лучше с ним
  acme_challenge:       # ← специально для HTTP-01 челленджа

services:
  db:
    image: postgres:15
    volumes:
      - pg_data:/var/lib/postgresql/data
    env_file:
      - .env

  backend:
    container_name: foodgram-backend
    image: sadons/foodgram_backend
    env_file: .env
    volumes:
      - static:/backend_static
      - media:/app/media
    depends_on:
      - db

  frontend:
    container_name: foodgram-front
    image: sadons/foodgram_frontend
    command: cp -r /app/result_build/. /static/
    volumes:
      - static:/static

  nginx:
    container_name: foodgram-proxy
    image: nginx:1.25.4-alpine
    ports:
      - "80:80"
      - "443:443"                    # ← добавил 443 порт
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static:/backend_static
      - media:/media                  # если отдаёшь медиа через nginx
      - letsencrypt_etc:/etc/letsencrypt          # ← критически важно
      - acme_challenge:/webroot                   # ← для челленджа
    depends_on:
      - backend
      - frontend